### PR TITLE
Fix potential deadlock when `pipe(1)` is used

### LINKED ISSUE #167: Potential deadlock for multi-threaded programs when `pipe(1)` is used
If pipe(2) is unavailable (`iOS`, `macOS`) or fails and falls back to using `pipe(1)`, then `O_CLOEXEC` cannot be set atomically. There is a brief moment between the pipes being opened with `pipe(1)`, and when `fcntl` is called to set `FD_CLOEXEC` for each end of the pipe. If another `fork` call on a different thread is performed before the flags can be set, then those descriptors will be leaked. If leaked, the `read` call in the parent process will not actually pop out when the child process the pipes were meant for successfully executes `execve`; the write end will not have all its descriptors closed on it until that **other** process exits.

As of #159 , the `posixSpawn` implementation is also affected by this.

Having some sort of global lock to acquire when using `pipe(1)` and `fork`, as seen in some other codebases, is out of the question. That would only work if every single codebase used `kmp-process` to spawn new processes.

I think both implementations must utilize `O_NONBLOCK` with the pipes, and then set a limit on the number of `read` retries depending on which version of `pipe` was used. So, for example:
    - `pipe(1)` -> 100ms worth of retries
    - `pipe(2)` -> infinite retries

A retry for a `read` operation would occur when it returns -1 with an `errno` of `EINTR`, `EAGAIN`, or `EWOULDBLOCK`. A retry would be made up of some `usleep` delay, then checking for a process exit code, then read again (until number of retries is exceeded).

### PR DESCRIPTION
**Pull request by 05nelsonm**
Closes #167

### CODE REVIEW

File: library/process/src/unixMain/kotlin/io/matthewnelson/kmp/process/internal/UnixPlatform.kt [hunk 1]
```diff
@@ -18,9 +18,151 @@
...
+        if (code != null && code != 0) threw = onNonZeroExitCode(code)
+    }
+
+    try {
+        pipe.close()
+    } catch (e: IOException) {
+        if (threw != null) {
+            threw.addSuppressed(e)
+        } else {
+            threw = IOException("CLOEXEC pipe failure", e)
```
Comment (05nelsonm) [inline library/process/src/unixMain/kotlin/io/matthewnelson/kmp/process/internal/UnixPlatform.kt:161]: If `threw` is null here, there should be a check for what `code` is.

Comment (05nelsonm) [reply library/process/src/unixMain/kotlin/io/matthewnelson/kmp/process/internal/UnixPlatform.kt]: Resolved in commit 94a7cf8
