### PR TITLE
Fix program path finding for UNIX sources

### LINKED ISSUE #80: program path should only be utilized for `forkExec`
Because `execvep` is unavailable and are using `execve`, we have to find the program path ourselves when it is not an absolute or relative path. (e.g. `command = "sh"`)

There are 2 options:
 - Use `execvp` and replace the fork environment with the environment passed.
 - Use `execve` and try all programs with that name available within the `PATH` environment variable.

### PR DESCRIPTION
**Pull request by 05nelsonm**
Closes #80

### CODE REVIEW

File: library/process/src/unixMain/kotlin/io/matthewnelson/kmp/process/internal/PlatformBuilder.kt [hunk 1]
```diff
@@ -80,7 +79,7 @@ internal actual class PlatformBuilder private actual constructor() {
         }
 
         try {
-            return forkExec(command, program, args, chdir, env, handle, destroy)
+            return forkExec(command, args, chdir, env, handle, destroy)
```
Comment (05nelsonm) [inline library/process/src/unixMain/kotlin/io/matthewnelson/kmp/process/internal/PlatformBuilder.kt:82]: use `programPaths` in constructor

Comment (05nelsonm) [reply library/process/src/unixMain/kotlin/io/matthewnelson/kmp/process/internal/PlatformBuilder.kt]: Resolved in commit 4871fbc
