### PR TITLE
Fix `Output` UTF-8 `stdout`/`stderr` not matching exactly what `Process` output

### LINKED ISSUE #229: `Output` UTF-8 from `stderr` and `stdout` does not match exactly what the process output
Previous to #227 , output was being fed through the `LineBreakOutFeed` and then concatenating all lines with a `\n` separator character. This automatically meant that something like `echo` from running `sh` would have it's final line trimmed off. Additionally, if the process has platform specific output, such as windows using `CRLF`, that is not being preserved.

This is **incorrect** behavior and should instead provide the **non-modified** output of the process as UTF-8 text.

### PR DESCRIPTION
**Pull request by 05nelsonm**
Closes #229

### CODE REVIEW

File: library/process/src/jsWasmJsMain/kotlin/io/matthewnelson/kmp/process/internal/PlatformBuilder.kt [hunk 1]
```diff
@@ -342,9 +342,7 @@ private fun JsBuffer?.toBufferedOutput(): Output.Buffered {
     if (this == null) return OutputFeedBuffer.EMPTY_OUTPUT
     val buf = this.asBuffer()
 
-    // TODO: Issue #229
-    var len = buf.length.toInt()
-    if (len > 0 && buf.readInt8(len - 1) == LF) len--
```
Comment (05nelsonm) [inline library/process/src/jsWasmJsMain/kotlin/io/matthewnelson/kmp/process/internal/PlatformBuilder.kt]: Remove unused import `LF`

**Review by 05nelsonm — COMMENTED** [review]
.
